[package]
edition = "2021"
name = "advent"
version = "0.1.0"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
nom = "7.1.3"
reqwest = { version = "0.11.22", features = ["blocking"] }

[workspace]
members = [
    "advent2024",
    "daily-template",
]
